name = "ReversibleSeismic"
uuid = "d4ee886f-91f1-4397-94bb-6bce6ba0d2e1"
authors = ["GiggleLiu <cacate0129@gmail.com> and contributors"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
